name: SSL Certificate Renewal Check
on:
  schedule:
    - cron: "0 0 * * 0" # weekly
jobs:
  ssl-check:
    name: Check SSL Certificate Expiry
    runs-on: ubuntu-latest
    steps:
      - name: Check frontend SSL expiry
        run: |
          echo | openssl s_client -servername <YOUR_STATIC_WEB_APP_URL> -connect <YOUR_STATIC_WEB_APP_URL>:443 2>/dev/null | openssl x509 -noout -dates
      - name: Check backend SSL expiry
        run: |
          echo | openssl s_client -servername <YOUR_BACKEND_APP_SERVICE_URL> -connect <YOUR_BACKEND_APP_SERVICE_URL>:443 2>/dev/null | openssl x509 -noout -dates
